// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBvoDP4SK7fiZyB3m_-5izhKZ7OhAGwqM',
    appId: '1:103983460473:web:809f09553b49bed9f7e4a8',
    messagingSenderId: '103983460473',
    projectId: 'myproject-a1877',
    authDomain: 'myproject-a1877.firebaseapp.com',
    storageBucket: 'myproject-a1877.firebasestorage.app',
    measurementId: 'G-RKJHSLQ4SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtdLOQtfJHZDokKUK2tzRZVw_xjPd8xXA',
    appId: '1:103983460473:android:d8632be9103f462ef7e4a8',
    messagingSenderId: '103983460473',
    projectId: 'myproject-a1877',
    storageBucket: 'myproject-a1877.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLAQixjp6HpwkJJeiX0jryOx-OZbajnVQ',
    appId: '1:103983460473:ios:f517c20852f7254bf7e4a8',
    messagingSenderId: '103983460473',
    projectId: 'myproject-a1877',
    storageBucket: 'myproject-a1877.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLAQixjp6HpwkJJeiX0jryOx-OZbajnVQ',
    appId: '1:103983460473:ios:f517c20852f7254bf7e4a8',
    messagingSenderId: '103983460473',
    projectId: 'myproject-a1877',
    storageBucket: 'myproject-a1877.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBvoDP4SK7fiZyB3m_-5izhKZ7OhAGwqM',
    appId: '1:103983460473:web:b6bbc32cfe853c36f7e4a8',
    messagingSenderId: '103983460473',
    projectId: 'myproject-a1877',
    authDomain: 'myproject-a1877.firebaseapp.com',
    storageBucket: 'myproject-a1877.firebasestorage.app',
    measurementId: 'G-02MNDEMYTT',
  );
}
